---
dependencies:
  - role: docker-server-linode
    when: ansible_bios_version | search('qemu-project.org')
  - role: docker-server-aws
    when: ansible_bios_version | search('amazon')
  - { role: nginx-passenger }
  - { role: ruby }
  - { role: mysql }
  - { role: backups }
  - { role: redis }
  - { role: newrelic-sysmond }
  - { role: discourse }
  - { role: mitmproxy }
  - role: f500.elasticsearch
    elasticsearch_network_host: localhost
  - role: nickhammond.logrotate
    logrotate_scripts:
      - name: rails
        path: "/var/www/shared/log/*.log"
        options:
          - daily
          - rotate 7
          - compress
          - missingok
          - copytruncate
