---
- name: Ensure curl is installed
  apt: pkg=curl

- name: Install gpg key for rvm
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  become_user: deploy

# TODO: Maybe install rvm by installing the package ruby-rvm?
- name: Ensure rvm installed in deploy user
  shell: curl -sSL https://get.rvm.io | bash -s stable creates=/home/deploy/.rvm
  become_user: deploy

# TODO: Is it possible to extract this list of dependencies automatically from rvm?
# Or allow rvm to do the install - but that would require the deploy user to have the permissions
- name: "Ensure ruby-2.3.1 dependencies installed"
  apt: pkg={{ item }}
  with_items:
    - patch
    - gawk
    - g++
    - make
    - patch
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - autoconf
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - libtool
    - bison
    - pkg-config
    - libffi-dev
    - libreadline6-dev
    - zlib1g-dev
    - libssl-dev
    - libgmp-dev

- name: Ensure ruby-2.3.1 is installed through rvm
  command: /bin/sh -l -c 'rvm install ruby-2.3.1 --autolibs=read-fail' creates=/home/deploy/.rvm/rubies/ruby-2.3.1
  become_user: deploy
  notify: Make ruby-2.3.1 the default

- name: Install bundler
  command: bash -lc "rvm ruby-2.3.1; gem install bundler"
  become_user: deploy
