---
#
# Adapted from https://github.com/jprichardson/ansible-redis
#
- name: Set os overcommit memory setting for redis
  sysctl: name=vm.overcommit_memory value=1
- name: ensure necessary packages installed
  apt: pkg={{ item }} state=latest
  with_items:
    - make
    - build-essential
    - tcl8.5

- name: Add redis-server PPA
  apt_repository:
    repo: 'ppa:chris-lea/redis-server'

- name: Install Redis package
  apt: pkg=redis-server

- name: Setup redis.conf
  copy: src=redis.conf dest=/etc/redis/redis.conf group=redis owner=redis
  register: redis_config

- name: Restart redis-server if config has changed
  service: name=redis-server state=restarted
  when: redis_config.changed

- name: Ensure redis-server service is started
  service: name=redis-server state=started enabled=yes
