---
# This playbook is for provisioning on a Linode box. It should be at least a Linode 2048 box and have
# 64 bit Ubuntu 12.04 LTS with 256 MB swap (I think).
#
# To run in development:
# vagrant provision local
#
# To run in production:
# cd provisioning
# ansible-playbook --user=root -i hosts playbook.yml
#
- hosts: all
  become: yes
  become_user: root
  roles:
    - morph-app
